#!/bin/bash

VERSION=0.1.2
BASEDIR=lorank8-$VERSION

cd Lorank 
g++ -O2 -Wall ResetIC880A.cpp -o ResetIC880A
cd ..

mkdir -p $BASEDIR/
cd $BASEDIR/
rm -rf *
git clone https://github.com/Ideetron/packet_forwarder.git
git clone https://github.com/Ideetron/lora_gateway.git
cp ../Lorank/library.cfg lora_gateway/libloragw/library.cfg
cd lora_gateway
git checkout -q Lorank_v$VERSION
make
cd ../packet_forwarder
git checkout -q Lorank_v$VERSION
make
cd ..
