#!/bin/bash

# start me like: install lorank8v1 1.0.1
# from the directory you cloned the repro Lorank in.

HWTARGET=$1
SWVERSION=$2

# Set the Lorank installation software to the correct release.
pushd Lorank
if [[ $SWVERSION != "" ]]; then git checkout -q Lorank_v$SWVERSION; fi
popd

# Start the platform dependent installation for this release.
./Lorank/$HWTARGET/install $SWVERSION

# We are done, next time we boot, this all should work
shutdown -h now
