#!/bin/bash

# Start this script once to modify a new Beagle Bone
# In the directory you cloned the repro Lorank in.

TARGETDIR=lorank8v1
DOGTAG=$(md5sum /etc/dogtag)
DTSHORT=${DOGTAG:0:5}

# Stop on the first sign of trouble
set -e

# Check if we start at the correct location
if [ ! -d Lorank ]
then
  echo "ERROR: Invalid working directory, does not contain the Lorank directory"
  exit 1
fi

if [ ! -d Lorank/$TARGETDIR/$DTSHORT ]
then
  echo "ERROR: Beagle Bone Release not known, no initialization possible"
  exit 1
fi

# Make dir for the system files we are about to modify
mkdir -p /root/savesys

# Load a basic webpage
if [ -e /var/lib/cloud9/index.html ]
then
  WT=/var/lib/cloud9
  cp -n $WT/index.html /root/savesys/cloud9_index.html
elif [ -e /usr/share/bone101/index.html ]
then
  WT=/usr/share/bone101
  cp -n $WT/index.html /root/savesys/bone101_index.html
else
  echo "Could find not index.html file to patch."
  exit 1
fi
mkdir -p $WT/images
cp Lorank/$TARGETDIR/index.html  $WT/index.html
cp Lorank/$TARGETDIR/login.html  $WT/login.html
cp Lorank/$TARGETDIR/photo.jpg   $WT/images/photo.jpg

# Patch the bonescript file, if possible
if [ -e /usr/local/lib/node_modules/bonescript/index.js ]
then
  cp -n     /usr/local/lib/node_modules/bonescript/index.js  /root/savesys/bonescript_index.js
  cp -n     /usr/local/lib/node_modules/bonescript/server.js /root/savesys/bonescript_server.js
  patch -lN /usr/local/lib/node_modules/bonescript/index.js  Lorank/$TARGETDIR/$DTSHORT/index.js.patch  || true
  patch -lN /usr/local/lib/node_modules/bonescript/server.js Lorank/$TARGETDIR/$DTSHORT/server.js.patch || true
elif [ -e /usr/local/lib/node_modules/bonescript/src/index.js ]
then
  cp -n     /usr/local/lib/node_modules/bonescript/src/index.js  /root/savesys/bonescript_src_index.js
  cp -n     /usr/local/lib/node_modules/bonescript/src/server.js /root/savesys/bonescript_src_server.js
  patch -lN /usr/local/lib/node_modules/bonescript/src/index.js  Lorank/$TARGETDIR/$DTSHORT/index.js.patch  || true
  patch -lN /usr/local/lib/node_modules/bonescript/src/server.js Lorank/$TARGETDIR/$DTSHORT/server.js.patch || true
else
  echo "Could find not bonescript index.js file to patch."
  exit 1
fi

# Localize files for off-line use
wget -nv -nc -P $WT/static https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
wget -nv -nc -P $WT/static https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css.map
wget -nv -nc -P $WT/static https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
wget -nv -nc -P $WT/static https://code.jquery.com/jquery-1.12.2.min.js

# install additional nodeJS modules
NPM_MODS="passport passport-local body-parser express-session connect-ensure-login" 
pushd /usr/local/lib/node_modules/bonescript
npm install $NPM_MODS
popd
