#!/bin/bash

# Start this script once to modify a new BBB
# In the directory you cloned the repro Lorank in.

TARGETDIR=lorank8v1
DOGTAG=$(md5sum /etc/dogtag)
DTSHORT=${DOGTAG:0:5}

# Stop on the first sign of trouble
set -e

# Check if we start at the correct location
if [ ! -d Lorank ]
then 
  echo "ERROR: Invalid working directory, does not contain the Lorank directory"
  exit 1
fi

if [ ! -d Lorank/$TARGETDIR/$DTSHORT ]
then 
  echo "ERROR: BBB Release not know, no initialization possible"
  exit 1
fi

# Make dir for the system files we are about to modify
mkdir -p /root/savesys

# Make the Lorank platform specific software 
pushd Lorank/$TARGETDIR
g++ -O2 -Wall ResetIC880A.cpp -o ResetIC880A
popd

# Make sure lorank gets to be a service after boottime
cp Lorank/$TARGETDIR/lorank.service /lib/systemd/system/
systemctl enable lorank.service

# Disable HDMI on the BBB
if [ -e /boot/uEnv.txt ] 
then 
  cp -a /boot/uEnv.txt /root/savesys/boot_uEnv.txt
  patch /boot/uEnv.txt Lorank/$TARGETDIR/$DTSHORT/uEnv.patch 
elif [ -e /boot/uboot/uEnv.txt ] 
then
  cp -a /boot/uboot/uEnv.txt /root/savesys/boot_uboot_uEnv.txt
  patch /boot/uboot/uEnv.txt Lorank/$TARGETDIR/$DTSHORT/uEnv.patch 
else
  echo "Could not patch uEnv.txt"
  exit 1
fi

# Set the hostname to lorank8
BBBNAME=$(hostname)
NEWNAME="lorank8"
hostname $NEWNAME
echo $NEWNAME > /etc/hostname
sed -i "s/$BBBNAME/$NEWNAME/" /etc/hosts

# Load a basic webpage
mkdir -p /var/lib/cloud9/images
mv /var/lib/cloud9/index.html /root/savesys/cloud9_index.html
cp /usr/local/lib/node_modules/bonescript/index.js /root/savesys/bonescript_index.js
cp Lorank/$TARGETDIR/index.html /var/lib/cloud9/
cp Lorank/$TARGETDIR/photo.jpg  /var/lib/cloud9/images/
patch /usr/local/lib/node_modules/bonescript/index.js Lorank/$TARGETDIR/index.js.patch

# Generate a key-pair so you can enable remote maintenance
if [ ! -e /root/.ssh/id_rsa ] 
then 
  ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa
fi

# Localize files for off-line use
wget -nv -nc -P/var/lib/cloud9/static https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
wget -nv -nc -P/var/lib/cloud9/static https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
wget -nv -nc -P/var/lib/cloud9/static https://code.jquery.com/jquery-1.12.0.min.js

# Get the ngrok binairy for remote maintenance
if [ ! -e /usr/bin/ngrok ] 
then
  wget -nv https://github.com/Ideetron/Lorank/raw/master/lorank8v1/ngrok_2.0.19.gz 
  gunzip ngrok_2.0.19.gz 
  mv ngrok_2.0.19 /usr/bin/ngrok
  chmod u+x /usr/bin/ngrok
fi   

# Disable the default debian login
passwd debian -l 

# Set a password for the root (user must change this on first use!)
echo "root:LorankAdmin" | chpasswd 
