#!/bin/bash

# This part contains the installation of proprietary software

TARGETDIR=lorank8v1
DOGTAG=$(md5sum /etc/dogtag)
DTSHORT=${DOGTAG:0:5}

# Stop on the first sign of trouble
set -e

# Check if we start at the correct location
if [ ! -d Lorank ]
then
  echo "ERROR: Invalid working directory, does not contain the Lorank directory"
  exit 1
fi

if [ ! -d Lorank/$TARGETDIR/$DTSHORT ]
then
  echo "ERROR: BBB Release not known, no initialization possible"
  exit 1
fi

# Make necessary directories
mkdir -p Lorank/Ngrok
mkdir -p Lorank/Loriot

# Get the ngrok binairy for remote maintenance
pushd Lorank/Ngrok
wget -nv -N https://github.com/Ideetron/Lorank/raw/master/$TARGETDIR/ngrok_2.3.25.gz
gunzip -c ngrok_2.3.25.gz > /usr/bin/ngrok
chown root:root /usr/bin/ngrok
chmod u+x /usr/bin/ngrok
popd

# Get the Loriot packet forwarder
pushd Lorank/Loriot
wget -nv -N https://github.com/Ideetron/Lorank/raw/master/$TARGETDIR/$DTSHORT/loriot_lorank_8_iC880A_SPI_latest.tgz
tar xf loriot_lorank_8_iC880A_SPI_latest.tgz
mv loriot_lorank_8_iC880A_SPI_*[^.tgz] loriot_pkt_fwd
chown root:root loriot_pkt_fwd
chmod a+x loriot_pkt_fwd
popd

# Install certificates for Loriot.
apt-get install -qq ca-certificates
