#!/bin/bash

# Start this script with the software version number as argument
# In the directory you cloned the repro Lorank in.
# This script is NOT suitable for upgrading, but only for one time
# initialization of a clean BeagleBordBlack.

VERSION=$1
HWTARGET=lorank8v1

# Stop on the first sign of trouble
set -e

# Check if a version is supplied (obligatory at this point)
if [[ $VERSION == "" ]]
then 
  echo "WARNING: No version number supplied, use latest."
fi

# Check if we start at the correct location
if [ ! -d Lorank ]
then 
  echo "ERROR: Invalid working directory, does not contain the Lorank directory"
  exit 1
fi

# Initialize the BeagleBordBlack for first use.
./Lorank/$HWTARGET/init_bbb 

# Install the lora suite. 
./Lorank/$HWTARGET/lora_suite $VERSION

