#!/bin/bash

# Start this script with the software version number as argument
# In the directory you cloned the repro Lorank in.
# This script is NOT suitable for upgrading, but only for one time
# initialization of a clean Beagle Bone.

# Control of urs leds
function led_on    { pushd /sys/class/leds/beaglebone\:green\:usr$1; echo none  > trigger; echo 1 > brightness; popd; }
function led_off   { pushd /sys/class/leds/beaglebone\:green\:usr$1; echo none  > trigger; echo 0 > brightness; popd; }
function led_flash { pushd /sys/class/leds/beaglebone\:green\:usr$1; echo timer > trigger; echo 50 > delay_on; echo 100 > delay_off; popd; }
function led_blank { led_off 0;   led_off 1;   led_off 2;   led_off 3;   }
function led_error { led_flash 0; led_flash 1; led_flash 2; led_flash 3; }

VERSION=$1
HWTARGET=lorank8v1
DOGTAG=$(md5sum /etc/dogtag)
DTSHORT=${DOGTAG:0:5}

# Stop on the first sign of trouble
set -e

# Check if a version is supplied (obligatory at this point)
if [[ $VERSION == "" ]]
then
  echo "WARNING: No version number supplied, use latest."
fi

# Check if we start at the correct location
if [ ! -d Lorank ]
then
  echo "ERROR: Invalid working directory, does not contain the Lorank directory"
  exit 1
fi

if [ ! -d Lorank/$HWTARGET/$DTSHORT ]
then
  echo "ERROR: BBB Release not known, no initialization possible"
  exit 1
fi


# report progress
led_flash 0
sleep 1

# Initialize the BeagleBone for first use.
./Lorank/$HWTARGET/init_bbb

# Perform the platform dependent initialization.
./Lorank/$HWTARGET/$DTSHORT/init_form

# Install the auxiliary software
./Lorank/$HWTARGET/init_aux


# report progress
led_on 0
led_flash 1
sleep 1

# Install the website
./Lorank/$HWTARGET/init_web


# report progress
led_on 1
led_flash 2
sleep 1

# Install the proprietary software
./Lorank/$HWTARGET/init_prop


# report progress
led_on 2
led_flash 3
sleep 1

# Install the lora suite.
./Lorank/$HWTARGET/lora_suite $VERSION


# We are done
led_on 3
sleep 1

