#! /bin/bash

# Test the connection, wait if needed.
while [[ $(ping -c1 google.com 2>&1 | grep " 0% packet loss") == "" ]]; do
  echo "lorank: waiting for internet connection ... "
  sleep 30
  done

# Reset the concentrator board and fire up the forwarder.  
./ResetIC880A  
./poly_pkt_fwd
