#!/bin/bash

# Start this script to remove Lorank and modifications
# In the directory you cloned the repro Lorank in.
# option "--force" is required to start.

TARGETDIR=lorank8v1

# Stop on the first sign of trouble
set -e

if [ ! -d Lorank ]
then
  echo "ERROR: Invalid working directory, does not contain the Lorank directory"
  exit 1
fi

if [[ $1 != "--force" ]]
then
  echo "INFO: Option --force is required to prevent accidental wiping of Lorank services."
  echo "This script deletes Lorank software AND bootup services required to reset hardware."
  echo "There are valid reasons for use, but a simple software upgrade is NOT one of them."
  echo "After a wipe, complete reinstall of lora software is required, use with extreme care."
  echo "In case of doubt, do NOT use."
  exit
fi

# Remove the Lorank directory (of which everything is a child)
rm -rf Lorank
rm -rf lorank*


# Restore the boot environment
if [ -e /root/savesys/boot_uEnv.txt ]
then
  cp -af /root/savesys/boot_uEnv.txt /boot/uEnv.txt
fi

if [ -e /root/savesys/boot_uboot_uEnv.txt ]
then
  cp -af /root/savesys/boot_uboot_uEnv.txt /boot/uboot/uEnv.txt
fi

# Restore the system environment
if [ -e /root/savesys/sshd_config ]
then
  cp -af /root/savesys/sshd_config /etc/ssh/sshd_config
fi

# Restore the webpage
if [ -e /root/savesys/cloud9_index.html ]
then
  rm -f /var/lib/cloud9/login.html
  rm -f /var/lib/cloud9/images/photo.jpg
  cp -af /root/savesys/cloud9_index.html /var/lib/cloud9/index.html 2>/dev/null || :
elif [ -e /root/savesys/bone101_index.html ]
  rm -f /usr/share/bone101/login.html
  rm -f /usr/share/bone101/images/photo.jpg
  cp -af /root/savesys/bone101_index.html /usr/share/bone101/index.html 2>/dev/null || :
else
  echo "Cannot restore the default webpage. Sorry."
fi

# Restore the bonescript
cp -af /root/savesys/bonescript_index.js       /usr/local/lib/node_modules/bonescript/index.js       2>/dev/null || :
cp -af /root/savesys/bonescript_server.js      /usr/local/lib/node_modules/bonescript/server.js      2>/dev/null || :
cp -af /root/savesys/bonescript_src_index.js   /usr/local/lib/node_modules/bonescript/src/index.js   2>/dev/null || :
cp -af /root/savesys/bonescript_src_server.js  /usr/local/lib/node_modules/bonescript/src/server.js  2>/dev/null || :

# Remove Lorank startup services
systemctl stop lorank.service
systemctl disable lorank.service
rm -f /lib/systemd/system/lorank.service


# Remove all ssh related stuff
rm -rf /root/.ssh


# Reenable the debian (default) user
passwd debian -u


# Remove the root password
passwd -d root
